# Generated by Django 5.2.2 on 2025-06-05 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_info', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='image',
        ),
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='school',
            name='measurement_chart',
        ),
        migrations.RemoveField(
            model_name='uniform',
            name='image',
        ),
        migrations.RemoveField(
            model_name='uniform',
            name='name',
        ),
        migrations.AddField(
            model_name='school',
            name='image_url',
            field=models.URLField(default='https://res.cloudinary.com/dhkagydmu/image/upload/v1748891941/city_view.jp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='logo_url',
            field=models.URLField(default='https://res.cloudinary.com/dhkagydmu/image/upload/v1748891941/city_view.jp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniform',
            name='image_url',
            field=models.URLField(default='https://res.cloudinary.com/dhkagydmu/image/upload/v1748891941/city_view.jp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniform',
            name='title',
            field=models.CharField(default='Dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='measurement_scale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.measurementscale'),
        ),
    ]
